language: node_js
sudo: required
cache:
  - apt
env:
  - NODE_ENV=test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
node_js:
  - "5"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 20
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - mongo uptime2-test --eval 'db.addUser("uptime2-test-user", "password");'
  - mongo uptime2-dev --eval 'db.addUser("uptime2-dev-user", "password");'
services: mongodb
matrix:
    fast_finish: true
    allow_failures:
     - node_js: "0.10"
     - node_js: "0.11"
     - node_js: "0.12"
script:
  - 'node app &'
  - 'make'
notifications:
  email: false
